# Generated by Django 5.1.6 on 2025-02-15 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('due_date', models.DateField(max_length=100)),
                ('status', models.BooleanField(max_length=100)),
            ],
        ),
    ]
